services:
    # Postgresql Database
    pgdb:
        image: postgres:13-alpine
        ports:
            - 5437:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mypasswd
        volumes:
            - ./docker/pgdb/data:/docker-entrypoint-initdb.d

    # Common image for development and build
    common:
        image: static_php_common
        build:
            context: ./
            dockerfile: ./docker/common/Dockerfile
        env_file:
            - .env
        volumes:
            - ./:/srv/sites/web_mounted:cached

    # Development service
    develop:
        build:
            context: ./docker/develop
        env_file:
            - .env
        ports:
            - "5010:5000"
        volumes:
            - ./:/srv/sites/web_mounted:cached
        depends_on:
            - common
            - pgdb

    # Build service
    build:
        build:
            context: ./docker/build
        env_file:
            - .env
        volumes:
            - ./dist:/srv/sites/web/dist:cached
        depends_on:
            - common
